### ISSUE TITLE
Typo in new implementation of filter load in observate 

### ISSUE THREAD

**Issue by prappleizer** [bd-j/sedpy#1]
In the new code which allows for 2-column ascii filter file loading, there is a command np.genfromtext which should be np.genfromtxt, which is throwing a "module contains no attribute genfromtext" error and not letting the code progress!

**Comment by bd-j** [comment]
thanks! should be fixed now (3a8d7a1)

**Comment by prappleizer** [comment]
Another typo: There's actually a typo in the same line of code, inside the genfromtxt function, it should be unpack=True, not unpack=true (hence the variable declaration error).

**Comment by bd-j** [comment]
d'oh!  just pushed a fix, and actually tested it.  That should be the last bug (in that part of the code...) Sorry!

**Comment by bd-j** [comment]
@prappelizer can I close this?
