### ISSUE TITLE
add ALMA filters?

### ISSUE THREAD

**Issue by moustakas** [bd-j/sedpy#12]
Would be nice to have the ALMA filter curves for proposals, etc.

**Comment by bd-j** [comment]
Oooh. Does alma have passbands with sensitivity curves?  I can't find any in a quick search. Or do you just get a (calibrated) spectrum at some resolution that can then be integrated however?

**Comment by moustakas** [comment]
I should've done a bit more homework before posting an issue.  Looks like it's a fixed 7.5GHz bandwidth for continuum observations.
