### ISSUE TITLE
sedpy have an problem in its attributes!!

### ISSUE THREAD

**Issue by Kourosh76** [bd-j/sedpy#20]
I installed prospector package according to its installation guide, but now, my package only have observate, yanny and reference_spectra attributes and don't have attenuation, extinction, photometer, ds9region and modelgrid attributes according to its description in this [link](https://github.com/bd-j/sedpy#description)!!
how can I solve this?

![Screenshot from 2021-02-24 19-49-11](https://user-images.githubusercontent.com/43784713/109033185-9edb0000-76db-11eb-98c5-86e3ebe0ec51.png)

**Comment by bd-j** [comment]
Most of those modules  -- modelgrid, photometer, extinction -- are deprecated in favor of more standard packages like scipy.interpolate or photutils, but I have just pushed a commit to make sure that `attenuation` appears as an attribute.

Note that you can usually do `from sedpy import modulename` even if the module does not appear as an attribute.
