### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by dweisz** [bd-j/sedpy#3]
Trying to install using python3.4.4, and I get the following errors about print statements.  Otherwise, I think it looks python3.x compatible.

...
Extracting sedpy-0.1.0-py3.4.egg to /anaconda/lib/python3.4/site-packages
  File "/anaconda/lib/python3.4/site-packages/sedpy-0.1.0-py3.4.egg/sedpy/attenuation.py", line 242
    print "make sure of your power law breaks"
                                             ^
SyntaxError: Missing parentheses in call to 'print'

  File "/anaconda/lib/python3.4/site-packages/sedpy-0.1.0-py3.4.egg/sedpy/yanny.py", line 497
    print 'typedef is:\n',typedef
                        ^
SyntaxError: Missing parentheses in call to 'print'
...

**Comment by bd-j** [comment]
oh yeah.  that's the problem with scombine, for some reason I wasn't watching sedpy and didn't see this.  Fixing now.

**Comment by bd-j** [comment]
alright, sedpy should be working in python3 as of 3ceb47f9b18b918457833a3031367c3191e6cb67

**Comment by dweisz** [comment]
looks good now.  Thanks!
